package com.tinydeal.affiliate;
// Generated 2015-1-9 10:59:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AffiliateHistory generated by hbm2java
 */
public class AffiliateHistory  implements java.io.Serializable {


     private Long ahId;
     private String address;
     private String ip;
     private Date timeAt;
     private short ifRegister;
     private short ifBought;
     private String affiliateCode;
     private int ordersId;
     private int customersId;
     private int aflCustomersId;
     private String randomNumber;
     private Integer processStatus;
     private Date processDate;

    public AffiliateHistory() {
    }

	
    public AffiliateHistory(String address, String ip, Date timeAt, short ifRegister, short ifBought, String affiliateCode, int ordersId, int customersId, int aflCustomersId, String randomNumber) {
        this.address = address;
        this.ip = ip;
        this.timeAt = timeAt;
        this.ifRegister = ifRegister;
        this.ifBought = ifBought;
        this.affiliateCode = affiliateCode;
        this.ordersId = ordersId;
        this.customersId = customersId;
        this.aflCustomersId = aflCustomersId;
        this.randomNumber = randomNumber;
    }
    public AffiliateHistory(String address, String ip, Date timeAt, short ifRegister, short ifBought, String affiliateCode, int ordersId, int customersId, int aflCustomersId, String randomNumber, Integer processStatus, Date processDate) {
       this.address = address;
       this.ip = ip;
       this.timeAt = timeAt;
       this.ifRegister = ifRegister;
       this.ifBought = ifBought;
       this.affiliateCode = affiliateCode;
       this.ordersId = ordersId;
       this.customersId = customersId;
       this.aflCustomersId = aflCustomersId;
       this.randomNumber = randomNumber;
       this.processStatus = processStatus;
       this.processDate = processDate;
    }
   
    public Long getAhId() {
        return this.ahId;
    }
    
    public void setAhId(Long ahId) {
        this.ahId = ahId;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Date getTimeAt() {
        return this.timeAt;
    }
    
    public void setTimeAt(Date timeAt) {
        this.timeAt = timeAt;
    }
    public short getIfRegister() {
        return this.ifRegister;
    }
    
    public void setIfRegister(short ifRegister) {
        this.ifRegister = ifRegister;
    }
    public short getIfBought() {
        return this.ifBought;
    }
    
    public void setIfBought(short ifBought) {
        this.ifBought = ifBought;
    }
    public String getAffiliateCode() {
        return this.affiliateCode;
    }
    
    public void setAffiliateCode(String affiliateCode) {
        this.affiliateCode = affiliateCode;
    }
    public int getOrdersId() {
        return this.ordersId;
    }
    
    public void setOrdersId(int ordersId) {
        this.ordersId = ordersId;
    }
    public int getCustomersId() {
        return this.customersId;
    }
    
    public void setCustomersId(int customersId) {
        this.customersId = customersId;
    }
    public int getAflCustomersId() {
        return this.aflCustomersId;
    }
    
    public void setAflCustomersId(int aflCustomersId) {
        this.aflCustomersId = aflCustomersId;
    }
    public String getRandomNumber() {
        return this.randomNumber;
    }
    
    public void setRandomNumber(String randomNumber) {
        this.randomNumber = randomNumber;
    }
    public Integer getProcessStatus() {
        return this.processStatus;
    }
    
    public void setProcessStatus(Integer processStatus) {
        this.processStatus = processStatus;
    }
    public Date getProcessDate() {
        return this.processDate;
    }
    
    public void setProcessDate(Date processDate) {
        this.processDate = processDate;
    }




}


