package com.tinydeal.affiliate;
// Generated 2015-1-9 10:59:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * CustomersPoints generated by hbm2java
 */
public class CustomersPoints  implements java.io.Serializable {


     private Integer id;
     private Integer linkId;
     private Integer type;
     private BigDecimal points;
     private Date createtime;
     private Integer customersId;
     private String title;
     private String comment;
     private Integer generalPoint;
     private Short pointStatus;
     private float currentPoints;
     private float canUsePoints;
     private String relativeTableName;
     private Date lastModified;
     private Date omsUpdateTime;

    public CustomersPoints() {
    }

	
    public CustomersPoints(float currentPoints, float canUsePoints) {
        this.currentPoints = currentPoints;
        this.canUsePoints = canUsePoints;
    }
    public CustomersPoints(Integer linkId, Integer type, BigDecimal points, Date createtime, Integer customersId, String title, String comment, Integer generalPoint, Short pointStatus, float currentPoints, float canUsePoints, String relativeTableName, Date lastModified, Date omsUpdateTime) {
       this.linkId = linkId;
       this.type = type;
       this.points = points;
       this.createtime = createtime;
       this.customersId = customersId;
       this.title = title;
       this.comment = comment;
       this.generalPoint = generalPoint;
       this.pointStatus = pointStatus;
       this.currentPoints = currentPoints;
       this.canUsePoints = canUsePoints;
       this.relativeTableName = relativeTableName;
       this.lastModified = lastModified;
       this.omsUpdateTime = omsUpdateTime;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getLinkId() {
        return this.linkId;
    }
    
    public void setLinkId(Integer linkId) {
        this.linkId = linkId;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public BigDecimal getPoints() {
        return this.points;
    }
    
    public void setPoints(BigDecimal points) {
        this.points = points;
    }
    public Date getCreatetime() {
        return this.createtime;
    }
    
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    public Integer getCustomersId() {
        return this.customersId;
    }
    
    public void setCustomersId(Integer customersId) {
        this.customersId = customersId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Integer getGeneralPoint() {
        return this.generalPoint;
    }
    
    public void setGeneralPoint(Integer generalPoint) {
        this.generalPoint = generalPoint;
    }
    public Short getPointStatus() {
        return this.pointStatus;
    }
    
    public void setPointStatus(Short pointStatus) {
        this.pointStatus = pointStatus;
    }
    public float getCurrentPoints() {
        return this.currentPoints;
    }
    
    public void setCurrentPoints(float currentPoints) {
        this.currentPoints = currentPoints;
    }
    public float getCanUsePoints() {
        return this.canUsePoints;
    }
    
    public void setCanUsePoints(float canUsePoints) {
        this.canUsePoints = canUsePoints;
    }
    public String getRelativeTableName() {
        return this.relativeTableName;
    }
    
    public void setRelativeTableName(String relativeTableName) {
        this.relativeTableName = relativeTableName;
    }
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }
    public Date getOmsUpdateTime() {
        return this.omsUpdateTime;
    }
    
    public void setOmsUpdateTime(Date omsUpdateTime) {
        this.omsUpdateTime = omsUpdateTime;
    }




}


