package com.tinydeal.affiliate;
// Generated 2015-1-9 10:59:18 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * OrdersTotal generated by hbm2java
 */
public class OrdersTotal  implements java.io.Serializable {


     private Integer ordersTotalId;
     private int ordersId;
     private String title;
     private String text;
     private BigDecimal value;
     private String class_;
     private int sortOrder;
     private int storeModuleId;
     private String comments;
     private Date lastModified;

    public OrdersTotal() {
    }

	
    public OrdersTotal(int ordersId, String title, String text, BigDecimal value, String class_, int sortOrder, int storeModuleId) {
        this.ordersId = ordersId;
        this.title = title;
        this.text = text;
        this.value = value;
        this.class_ = class_;
        this.sortOrder = sortOrder;
        this.storeModuleId = storeModuleId;
    }
    public OrdersTotal(int ordersId, String title, String text, BigDecimal value, String class_, int sortOrder, int storeModuleId, String comments, Date lastModified) {
       this.ordersId = ordersId;
       this.title = title;
       this.text = text;
       this.value = value;
       this.class_ = class_;
       this.sortOrder = sortOrder;
       this.storeModuleId = storeModuleId;
       this.comments = comments;
       this.lastModified = lastModified;
    }
   
    public Integer getOrdersTotalId() {
        return this.ordersTotalId;
    }
    
    public void setOrdersTotalId(Integer ordersTotalId) {
        this.ordersTotalId = ordersTotalId;
    }
    public int getOrdersId() {
        return this.ordersId;
    }
    
    public void setOrdersId(int ordersId) {
        this.ordersId = ordersId;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public BigDecimal getValue() {
        return this.value;
    }
    
    public void setValue(BigDecimal value) {
        this.value = value;
    }
    public String getClass_() {
        return this.class_;
    }
    
    public void setClass_(String class_) {
        this.class_ = class_;
    }
    public int getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(int sortOrder) {
        this.sortOrder = sortOrder;
    }
    public int getStoreModuleId() {
        return this.storeModuleId;
    }
    
    public void setStoreModuleId(int storeModuleId) {
        this.storeModuleId = storeModuleId;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }




}


